version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8080"
    environment:
      - DATABASE_URL=file:./data/projectshelf.db
      - NODE_ENV=production
    volumes:
      - ./data:/app/data
    restart: unless-stopped
